version: '3.8'

services:
  mysql-db:
    image: zechih/carbonsense-db:53
    container_name: mysql-carbonsense
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carbondb
      MYSQL_USER: carbonuser
      MYSQL_PASSWORD: carbonpass
    ports:
      - "3306:3306"
    networks:
      - carbonsense-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  carbon-app:
    image: zechih/carbonsense-app:53
    container_name: carbon-app
    ports:
      - "8090:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/carbondb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: carbonuser
      SPRING_DATASOURCE_PASSWORD: carbonpass
    networks:
      - carbonsense-net

networks:
  carbonsense-net:
    driver: bridge
